# Credits

This is heavily influenced or copied from https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [3]:
import torch

Construct a 5x3 matrix, uninitialized

In [4]:
x = torch.Tensor(5, 3)
print(x)

tensor([[1.0561e-38, 1.0653e-38, 4.1327e-39],
        [8.9082e-39, 9.8265e-39, 9.4592e-39],
        [1.0561e-38, 1.0653e-38, 1.0469e-38],
        [9.5510e-39, 9.1837e-39, 1.0561e-38],
        [1.0469e-38, 9.0000e-39, 1.0653e-38]])


Construct a randomly initialized matrix

In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8931, 0.5676, 0.5507],
        [0.9828, 0.5377, 0.9726],
        [0.2835, 0.2930, 0.8474],
        [0.8781, 0.0708, 0.7648],
        [0.8046, 0.8566, 0.2499]])


Get its size

In [6]:
print(x.size())

torch.Size([5, 3])


**NOTE** `torch.Size` is in fact a tuple, so it supports the same operations

In [7]:
x[1:3] = 2
print(x)

tensor([[0.8931, 0.5676, 0.5507],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.8781, 0.0708, 0.7648],
        [0.8046, 0.8566, 0.2499]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [17]:
#1
x = torch.Tensor(2, 17)
print(x)


tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          2.7488e+12,  0.0000e+00,  2.8026e-45,  1.6486e+22,  1.6598e-11,
          4.5911e-41,  0.0000e+00],
        [ 0.0000e+00,  4.8042e+27,  9.1042e-12,  6.2609e+22,  4.7428e+30,
          7.3982e+20,  4.6228e+30,  1.8465e+25,  1.0901e+27,  1.6907e-01,
          1.7743e+28,  7.3272e+25,  2.6899e+36,         nan,  0.0000e+00,
         -1.9443e+32,  4.5909e-41]])


In [19]:
#2
x=torch.FloatTensor(3,1)
print(x)

tensor([[ 0.0000e+00],
        [ 0.0000e+00],
        [-1.8846e+32]])


In [23]:
#3
x=torch.LongTensor(5,2,1)
print(x)
x.fill_(7)

tensor([[[14355640430624878],
         [27584998696288348]],

        [[32651548277538908],
         [27303553780220005]],

        [[28992339220037731],
         [30962642582700133]],

        [[34058953225470069],
         [32088624092872796]],

        [[29555280582541413],
         [32088581144313966]]])


tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])

In [31]:
#4
x=torch.ByteTensor(5,)
x[0].fill_(0)
x[1].fill_(1)
x[2].fill_(1)
x[3].fill_(1)
x[4].fill_(0)

print(x)


tensor([0, 1, 1, 1, 0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.8641, 1.0394, 0.5984],
        [2.7253, 2.7996, 2.1828],
        [2.9912, 2.1336, 2.6769],
        [0.9649, 0.6994, 1.0376],
        [0.9831, 0.8829, 0.7776]])


### 2.2 Addition: syntax 2

In [9]:
print(torch.add(x, y))

tensor([[1.8641, 1.0394, 0.5984],
        [2.7253, 2.7996, 2.1828],
        [2.9912, 2.1336, 2.6769],
        [0.9649, 0.6994, 1.0376],
        [0.9831, 0.8829, 0.7776]])


### 2.3 Addition: giving an output tensor

In [10]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.8641, 1.0394, 0.5984],
        [2.7253, 2.7996, 2.1828],
        [2.9912, 2.1336, 2.6769],
        [0.9649, 0.6994, 1.0376],
        [0.9831, 0.8829, 0.7776]])


### 2.4 Addition: in-place

adds `x`to `y`

In [11]:
y.add_(x)
print(y)

tensor([[1.8641, 1.0394, 0.5984],
        [2.7253, 2.7996, 2.1828],
        [2.9912, 2.1336, 2.6769],
        [0.9649, 0.6994, 1.0376],
        [0.9831, 0.8829, 0.7776]])


**NOTE** Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [12]:
print(x[:, 1])

tensor([0.5676, 2.0000, 2.0000, 0.0708, 0.8566])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiply of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [47]:
#1
x = torch.randn(3, 3)
y = torch.randn(3)
ans1=torch.mul(x,y)
print(ans1)

tensor([[-0.1218,  0.3596,  0.7146],
        [-0.2178,  0.1403, -0.1769],
        [-0.1366, -0.5416, -0.1752]])


In [50]:
#2
x.mul_(y)
print(x)

tensor([[-0.1218,  0.3596,  0.7146],
        [-0.2178,  0.1403, -0.1769],
        [-0.1366, -0.5416, -0.1752]])


In [51]:
#3
ans2=torch.div(ans1,y)
print(ans2)

tensor([[ 0.1137,  0.9894,  0.7690],
        [ 0.2034,  0.3861, -0.1904],
        [ 0.1276, -1.4902, -0.1886]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [13]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [14]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [15]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [16]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [52]:
#1
a = torch.ones(5,2)
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [53]:
#2
b = a.numpy()
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [56]:
#3
a = torch.from_numpy(b)
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [54]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # this is meant as a tensor to be run on the GPU.
    # the .cuda() does this to any parameter it is applied to
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machie.")

tensor([[-0.1218,  0.3596,  0.7146],
        [-0.2178,  0.1403, -0.1769],
        [-0.1366, -0.5416, -0.1752]], device='cuda:0')
tensor([-1.0711,  0.3635,  0.9292], device='cuda:0')
tensor([[-1.1929,  0.7231,  1.6437],
        [-1.2889,  0.5038,  0.7523],
        [-1.2077, -0.1782,  0.7539]], device='cuda:0')
